# Generated by Django 4.2.14 on 2024-07-29 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestRoomInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='방 위치')),
                ('exclusive_overall_area', models.CharField(max_length=50, verbose_name='전용면적')),
                ('building_use', models.CharField(max_length=100, verbose_name='건물 용도')),
                ('deposit', models.CharField(blank=True, max_length=50, null=True, verbose_name='보증금')),
                ('monthly_rent', models.CharField(blank=True, max_length=50, null=True, verbose_name='월세')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('latest_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='최근 사용자')),
            ],
            options={
                'verbose_name': '최근 방 정보',
                'verbose_name_plural': '최근 방 정보 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
