# renew_before_expiry = 30 days
version = 2.11.0
archive_dir = /etc/letsencrypt/archive/houseadvisor.site
cert = /etc/letsencrypt/live/houseadvisor.site/cert.pem
privkey = /etc/letsencrypt/live/houseadvisor.site/privkey.pem
chain = /etc/letsencrypt/live/houseadvisor.site/chain.pem
fullchain = /etc/letsencrypt/live/houseadvisor.site/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = ccc5c7eca5b25d0f4feba81cf4b8dcad
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
houseadvisor.site = /var/www/certbot
