services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PATH=/usr/local/bin:$PATH
    depends_on:
      - rabbitmq
    mem_limit: 1g  # 메모리 제한 추가

  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile.rabbitmq
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypassword
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/advanced.config:/etc/rabbitmq/advanced.config

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=amqp://myuser:mypassword@rabbitmq:5672//
      - PATH=/usr/local/bin:$PATH
    depends_on:
      - rabbitmq
    mem_limit: 1g  # 메모리 제한 추가