FROM python:3.9-slim-bullseye

WORKDIR /app

# 패키지 설치
RUN apt-get update && apt-get install -y \
    git \
    default-libmysqlclient-dev \
    build-essential \
    pkg-config \
    chromium \
    chromium-driver \
    redis-tools && \
    curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# 사용자 및 그룹 생성
RUN groupadd -r myuser && useradd -r -g myuser myuser

# requirements.txt 파일 복사 및 종속성 설치
COPY requirements.txt ./
RUN pip install --upgrade pip && pip install -r requirements.txt && pip install celery python-dotenv gunicorn

# 앱 파일 복사
COPY . .

# 권한 설정
RUN chown -R myuser:myuser /app

# 개발환경 / 배포환경으로 나누었습니다!
ENV DJANGO_SETTINGS_MODULE=config.settings
CMD if [ "$DJANGO_ENV" = "production" ]; then gunicorn --bind 0.0.0.0:8000 config.wsgi:application; else python manage.py runserver 0.0.0.0:8000; fi

# 사용자 권한으로 실행
USER myuser
