services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PATH=/usr/local/bin:$PATH
      - PYTHONPATH=/app
    depends_on:
      - rabbitmq
      - redis

  daphne:
    build:
      context: .
      dockerfile: daphne/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PATH=/usr/local/bin:$PATH
      - PYTHONPATH=/app
    depends_on:
      - rabbitmq
      - redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile-celery
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - PATH=/usr/local/bin:$PATH
      - PYTHONPATH=/app
    depends_on:
      - rabbitmq

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/app/staticfiles
      - ./letsencrypt:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
      - daphne

  certbot:
    image: certbot/certbot
    user: root
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./letsencrypt:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email mocodoco@naver.com --agree-tos --no-eff-email -d houseadvisor.site
    depends_on:
      - nginx

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/advanced.config:/etc/rabbitmq/advanced.config
