
FROM python:3.9

WORKDIR /app

# 필요한 패키지 설치
RUN apt-get update \
    && apt-get install -y \
       git \
       default-libmysqlclient-dev \
       build-essential \
       wget \
       unzip \
       xvfb \
       libxi6 \
       libgconf-2-4 \
       gnupg2 \
       curl \
       chromium \
       chromium-driver \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# requirements.txt 파일 복사 및 종속성 설치
COPY requirements.txt ./
RUN pip install --upgrade pip && pip install -r requirements.txt && pip install celery python-dotenv

# 환경 변수 설정
ENV PYTHONUNBUFFERED=1
ENV DJANGO_SETTINGS_MODULE=config.settings

# 사용자 및 그룹 생성
RUN groupadd -r myuser && useradd -r -g myuser myuser

# 비루트 사용자로 실행
USER myuser

# 애플리케이션 파일 복사
COPY . .

CMD ["celery", "-A", "config", "worker", "--loglevel=info"]
