# Generated by Django 4.2.14 on 2024-07-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdetailinfo',
            name='image_url',
            field=models.URLField()),
    ]
