# Generated by Django 4.2.14 on 2024-07-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roominfo',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
