# Generated by Django 4.2.14 on 2024-07-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_auto_20240720_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdetailinfo',
            name='price',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
