# Generated by Django 4.2.14 on 2024-07-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_remove_roominfo_created_at_alter_roominfo_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roominfo',
            name='price',
            field=models.TextField(),
        ),
    ]
