# Generated by Django 4.2.14 on 2024-07-19 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0003_alter_roominfo_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomDetailInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
                ('exclusive_overall_area', models.TextField()),
                ('maintenance_fee', models.TextField()),
                ('room_type', models.TextField()),
                ('num_rooms_bathrooms', models.TextField()),
                ('floor_building_floors', models.TextField()),
                ('direction', models.TextField()),
                ('parking_availability', models.TextField()),
                ('total_parking_spaces', models.TextField()),
                ('heating_type', models.TextField()),
                ('building_use', models.TextField()),
                ('move_in_date', models.TextField()),
                ('approval_date', models.TextField()),
                ('initial_registration_date', models.TextField()),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='options.roominfo')),
            ],
        ),
    ]
