# Generated by Django 4.2.14 on 2024-07-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0004_roomdetailinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdetailinfo',
            name='layout_image_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
