# Generated by Django 4.2.14 on 2024-07-19 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0005_roomdetailinfo_layout_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomdetailinfo',
            name='layout_image_url',
        ),
    ]
