# 관리 콘솔 설정
management.listener.port = 15672

# 메시지 브로커 설정
listeners.tcp.default = 5672

loopback_users.guest = false
management.load_definitions = /etc/rabbitmq/definitions.json

deprecated_features.permit.management_metrics_collection = true
deprecated_features.permit.transient_nonexcl_queues = true
deprecated_features.permit.global_qos = true




