# Generated by Django 4.2.13 on 2024-07-09 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_username_customuser_auth_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='users_table',
        ),
    ]
