http {
    upstream django {
        server web:8000;
    }

    upstream daphne {
        server daphne:8001;
    }

    upstream frontend {
        server host.docker.internal:5173;
    }

    server {
        listen 80;
        server_name houseadvisor.site;

        location / {
            proxy_pass http://django;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_redirect off;
        }

        location /static/ {
            alias /app/staticfiles/;
        }

        location /ws/ {
            proxy_pass http://daphne;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /frontend/ {
            proxy_pass http://frontend;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_redirect off;
        }

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
            try_files $uri =404;
        }
    }
}

events {
    worker_connections 1024;
}
