# Generated by Django 4.2.13 on 2024-07-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=20)),
                ('apartment', models.BooleanField(default=False)),
                ('villa', models.BooleanField(default=False)),
                ('room', models.BooleanField(default=False)),
                ('yearly', models.BooleanField(default=False)),
                ('yearly_fee', models.IntegerField(blank=True, null=True)),
                ('deposit', models.IntegerField(blank=True, null=True)),
                ('monthly_fee', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
