# Generated by Django 4.2.13 on 2024-07-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='monthly',
            field=models.BooleanField(default=False),
        ),
    ]
