# Generated by Django 4.2.13 on 2024-07-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_category_monthly'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canParking', models.BooleanField(default=False)),
                ('hasElevator', models.BooleanField(default=False)),
                ('parkingNumRangeMin', models.IntegerField(choices=[(0, '상관없음'), (1, '1대 이상'), (2, '2대 이상')], default=0)),
                ('roomCount', models.IntegerField(choices=[(0, '상관없음'), (1, '1개'), (2, '2개'), (3, '3개'), (4, '4개 이상')], default=0)),
                ('isDivision', models.BooleanField(default=False)),
                ('isShortLease', models.BooleanField(default=False)),
                ('isDuplex', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Residences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.BooleanField(default=False)),
                ('officetel', models.BooleanField(default=False)),
                ('house', models.BooleanField(default=False)),
                ('onetwo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LEASE', models.BooleanField(default=False)),
                ('depositRangeMax', models.IntegerField(blank=True, null=True)),
                ('MONTHLY_RENT', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
