# Generated by Django 4.2.14 on 2024-07-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_options_regions_residences_types_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='regions',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regions',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
