# Generated by Django 4.2.14 on 2024-07-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0004_regions_latitude_regions_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='types',
            name='priceRangeMax',
            field=models.CharField(max_length=100, null=True, blank=True),
        ),
    ]
