# Generated by Django 4.2.14 on 2024-07-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0005_types_pricerangemax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='types',
            name='depositRangeMax',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='types',
            name='priceRangeMax',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
